use_frameworks!

platform :ios, '10.0'

target 'IQKeyboardReturnManager_Example' do
  pod 'IQKeyboardReturnManager', :path => '../'

  target 'IQKeyboardReturnManager_Tests' do
    inherit! :search_paths

    
  end
end
