use_frameworks!

platform :ios, '13.0'

target 'IQKeyboardReturnManager_Example' do
  pod 'IQKeyboardReturnManager', :path => '../'
  pod "SwiftLint"
end

target 'IQKeyboardReturnManager_ObjcExample' do
  pod 'IQKeyboardReturnManager', :path => '../'
end
